name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # Required for provenance for npm publish https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      HUSKY: 0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # with:
        #   version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Verify version
        uses: ./.github/actions/verify-npm-tag

      - name: Install
        run: pnpm install --frozen-lockfile

      # This builds the tarball and packs it into /dist
      - name: Build + Pack tarball
        run: pnpm run build:lib

      # This installs the tarball packed into /dist
      - name: Test tarball
        run: pnpm run build:test-install

      # This publishes the tarball packed into /dist to npm
      - name: Publish package to npm
        run: pnpm run build:publish  --provenance

      # This creates a GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: 'dist/*.tgz'
